#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

symbol_unctracked="\xE2\x96\xA1"   # □ WHITE SQUARE
symbol_added="\xE2\x96\xA0"        # ■ BLACK SQUARE
symbol_modified="\xE2\x97\x86"     # ◆ BLACK DIAMOND
symbol_renamed="\xE2\x97\x87"      # ◇ WHITE DIAMOND
symbol_deleted="\xE2\x97\x8C"      # ◌ DOTTED CIRCLE
symbol_typechanged="\xE2\x9A\x91"  # ❖ BLACK DIAMOND MINUS WHITE X
symbol_overall="\xE2\x9D\x96"      # ◔ CIRCLE WITH UPPER RIGHT QUADRANT BLACK

current_branch=""
in_hg_repo() {
    current_branch=$(hg branch 2> /dev/null)
    if [[ $current_branch ]]; then
        return 0
    fi
    return 1
}


cwd_added_files() {
    added_files_count=$(hg status | grep "^A" | wc -l | tr -d " ")
    if [[ $added_files_count > 0 ]]; then
        printf " ${symbol_added}:${added_files_count}"
    fi
}


cwd_modified_files() {
    modified_files_count=$(hg status | grep "^M" | wc -l | tr -d " ")
    if [[ $modified_files_count > 0 ]]; then
        printf " ${symbol_modified}:${modified_files_count}"
    fi
}

cwd_untracked() {
    files_not_under_revision_control_count=$(hg status | grep "^?" | wc -l | tr -d " ")
    if [[ $files_not_under_revision_control_count > 0 ]]; then
        printf " ${symbol_unctracked}:${files_not_under_revision_control_count}"
    fi
}

cwd_deleted_files() {
    deleted_files_count=$(hg status | grep "^R" | wc -l | tr -d " ")
    if [[ $deleted_files_count > 0 ]]; then
        printf " ${symbol_deleted}:${deleted_files_count}"
    fi
}

if [[ $(command -v hg) ]]; then
    if in_hg_repo; then
        commit_id=$(hg identify -ni 2> /dev/null | tr " " ":")

        any_added=$(cwd_added_files)
        any_modified=$(cwd_modified_files)
        any_untracked=$(cwd_untracked)
        any_deleted=$(cwd_deleted_files)
        
        branch_color="$(tput setaf 2)${current_branch}$(tput sgr0)"
        at_color="$(tput setaf 7)@$(tput sgr0)"
        
        echo "[${branch_color} ${at_color} ${commit_id}${any_untracked}${any_added}${any_modified}${any_deleted}]"
    fi
fi
