#!/usr/bin/env bash

if [[ $(command -v rbenv) ]]; then
    rbenv_version=$(rbenv version-name)
    if [[ $rbenv_version != "system" && ! -z $rbenv_version ]]; then
        rbenv_version="◆ ${rbenv_version}"
        if [[ $DFF_RBENV_PROMPT_COLOR ]]; then
            rbenv_version="${DFF_RBENV_PROMPT_COLOR}${rbenv_version}${COLOR_OFF}"
        fi
        printf "[${rbenv_version}]"
    fi
fi
